# Generated by Django 3.1.6 on 2022-07-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badec_app', '0002_auto_20220707_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='date_payement',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AddField(
            model_name='salle',
            name='nom',
            field=models.CharField(default='Salle 25', max_length=200),
        ),
    ]
