# Generated by Django 3.1.6 on 2022-07-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badec_app', '0003_auto_20220707_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='dept',
            field=models.ForeignKey(default='Consultance', on_delete=django.db.models.deletion.CASCADE, to='badec_app.departement'),
        ),
        migrations.AlterField(
            model_name='categorie_salle',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='disponibilite_salle',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='payement',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('projet_num', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField(default='')),
                ('date_fin', models.DateField(default='2022-01-01')),
                ('description', models.CharField(max_length=5000)),
                ('dept', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='badec_app.departement')),
            ],
        ),
    ]
